[project]
name = "dbos_transact"
version = "0.1.0"
description = "A Python framework for backends that scale"
authors = [
    {name = "DBOS, Inc.", email = "contact@dbos.dev"},
]
dependencies = [
    "pyyaml>=6.0.1",
    "jsonschema>=4.23.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.2.2",
    "mypy>=1.11.0",
    "pytest-mock>=3.14.0",
    "types-PyYAML>=6.0.12.20240311",
    "types-jsonschema>=4.23.0.20240712",
    "black>=24.4.2",
    "pre-commit>=3.7.1",
    "isort>=5.13.2",
]

[tool.isort]
profile = "black"
filter_files = true
atomic = true

[tool.mypy]
strict = true
exclude = "tests/"

[tool.pytest.ini_options]
addopts = "-s"
log_cli_format = "%(asctime)s [%(levelname)8s] (%(filename)s:%(lineno)s) %(message)s"
log_cli_level = "INFO"
log_cli = true