[project]
name = "dbos"
dynamic = ["version"]
description = "Ultra-lightweight durable execution in Python"
authors = [
    {name = "DBOS, Inc.", email = "contact@dbos.dev"},
]
dependencies = [
    "alembic>=1.13.3",
    "fastapi[standard]>=0.115.2",
    "jsonpickle>=3.3.0",
    "jsonschema>=4.23.0",
    "opentelemetry-api>=1.27.0",
    "opentelemetry-exporter-otlp-proto-http>=1.27.0",
    "opentelemetry-sdk>=1.27.0",
    "psutil>=6.0.0",
    "psycopg[binary]>=3.1", # Keep compatibility with 3.1--older Python installations/machines can't always install 3.2
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.2",
    "sqlalchemy[asyncio]>=2.0.36",
    "tomlkit>=0.13.2",
    "typer>=0.12.5",
    "typing-extensions>=4.12.2; python_version < \"3.10\"",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
dbos = "dbos.cli:app"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "scm"
version_format = "version:format_version"

[tool.pdm.dev-dependencies]
dev = [
    "black>=24.10.0",
    "confluent-kafka>=2.6.0",
    "flask>=3.0.3",
    "GitPython>=3.1.43",
    "httpx>=0.27.2",
    "isort>=5.13.2",
    "mypy>=1.12.0",
    "pdm-backend>=2.4.2",
    "pre-commit>=4.0.1",
    "pyjwt>=2.9.0",
    "pytest-asyncio>=0.24.0",
    "pytest-mock>=3.14.0",
    "pytest-order>=1.3.0",
    "pytest>=8.3.3",
    "pytz>=2024.2",
    "requests>=2.32.3",
    "types-confluent-kafka>=1.2.2",
    "types-jsonschema>=4.23.0.20240813",
    "types-psutil>=6.0.0.20240621",
    "types-PyYAML>=6.0.12.20240808",
    "types-requests>=2.32.0.20240914",
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
filter_files = true
atomic = true

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "-s"
log_cli_format = "%(asctime)s [%(levelname)8s] (%(name)s:%(filename)s:%(lineno)s) %(message)s"
log_cli_level = "INFO"
log_cli = true
