name: Run Chaos Tests

on:
    push:
      branches:
        - main
        - release/*
    pull_request:
      branches:
        - main
        - release/*
      types:
        - ready_for_review
        - opened
        - reopened
        - synchronize
    workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install Dependencies
      run: pdm install
      working-directory: ./

    - name: Run Chaos Tests
      run: pdm run pytest chaos-tests
      working-directory: ./