name: Run Unit Tests

on:
    push:
      branches:
        - main
        - release/*
    pull_request:
      branches:
        - main
        - release/*
      types:
        - ready_for_review
        - opened
        - reopened
        - synchronize
    workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest

    services:
      # Postgres service container
      postgres:
        image: sibedge/postgres-plv8
        env:
          # Specify the password for Postgres superuser.
          POSTGRES_PASSWORD: dbos
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
  
    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.9.x'
        architecture: 'x64'

    - name: Install Dependencies
      run: pdm install
      working-directory: ./

    - name: Run Unit Tests
      run: pdm run pytest
      working-directory: ./
      env:
        PGPASSWORD: dbos

    - name: Check Types
      run: pdm run mypy .
      working-directory: ./